@Api_HostAddress = http://localhost:5000

###
# Get a project by ID
GET {{Api_HostAddress}}/api/Projetos/2
Accept: application/json

###
# Get all projects with filters
GET {{Api_HostAddress}}/api/Projetos?IsPagination=true&PageIndex=1&PageSize=5
Accept: application/json

###
# Create a new project
POST {{Api_HostAddress}}/api/Projetos
Content-Type: application/json
Accept: application/json

{
    "id": 0,
    "nome": "Projeto Exemplo 1",
    "descricao": "Descrição do projeto 1",
    "dataCriacao": "2024-06-04T00:00:00"
}

###
# Update an existing project
PUT {{Api_HostAddress}}/api/Projetos/1
Content-Type: application/json
Accept: application/json

{
    "id": 1,
    "nome": "Projeto 1 Atualizado",
    "descricao": "Descrição atualizada",
    "dataCriacao": "2024-06-04T00:00:00"
}

###
# Delete a project by ID
DELETE {{Api_HostAddress}}/api/Projetos/1
Accept: application/json











### 
# Create a new Tarefa
POST {{Api_HostAddress}}/api/Tarefas
Content-Type: application/json
Accept: application/json

{
    "id": 0,
    "projetoId": 2,
    "titulo": "Nova tarefa 3",
    "descricao": "Descrição da tarefa",
    "dataVencimento": "2025-06-10T00:00:00",
    "statusId": 1,
    "prioridadeId": 2,
    "dataCriacao": "2025-06-06T00:00:00"
}

###
# Get a Tarefa by ID
GET {{Api_HostAddress}}/api/Tarefas/1
Accept: application/json

###
# Get all Tarefas with filters
GET {{Api_HostAddress}}/api/Tarefas?projetoId=1&statusId=1
Accept: application/json

###
# Update an existing Tarefa
PUT {{Api_HostAddress}}/api/Tarefas/1
Content-Type: application/json
Accept: application/json

{
    "id": 1,
    "projetoId": 1,
    "titulo": "Tarefa atualizada",
    "descricao": "Descrição atualizada",
    "dataVencimento": "2025-06-15T00:00:00",
    "statusId": 2,
    "prioridadeId": 3,
    "dataCriacao": "2025-06-06T00:00:00"
}

###
# Delete a Tarefa by ID
DELETE {{Api_HostAddress}}/api/Tarefas/1
Accept: application/json





















###
# Create a new Comentario
POST {{Api_HostAddress}}/api/Comentarios
Content-Type: application/json
Accept: application/json

{
  "id": 0,
  "tarefaId": 1,
  "autor": "Admin Sistema",
  "texto": "Comentário inicial sobre a tarefa.",
  "dataCriacao": "2025-06-07T10:00:00"
}

###
# Get a Comentario by ID
GET {{Api_HostAddress}}/api/Comentarios/1
Accept: application/json

###
# Get all Comentarios by TarefaId
GET {{Api_HostAddress}}/api/Comentarios?tarefaId=1
Accept: application/json

###
# Update an existing Comentario
PUT {{Api_HostAddress}}/api/Comentarios/1
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "tarefaId": 1,
  "autor": "João da Silva",
  "texto": "Comentário atualizado.",
  "dataCriacao": "2025-06-07T10:00:00"
}

###
# Delete a Comentario by ID
DELETE {{Api_HostAddress}}/api/Comentarios/1
Accept: application/json

